import ChakraProvider from '@/providers/chakra';
import { ColorModeProvider } from '@/providers/colorMode';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ColorModeProvider>
          <ChakraProvider>{children}</ChakraProvider>
        </ColorModeProvider>
      </body>
    </html>
  );
}
